module(name = "toolchains_llvm_mold_test")

bazel_dep(name = "mold", version = "2.40.4")
bazel_dep(name = "rules_cc", version = "0.2.25")
bazel_dep(name = "toolchains_llvm", version = "0.0.0")

local_path_override(
    module_name = "toolchains_llvm",
    path = "../..",
)

llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
inject_repo(llvm, "mold")
llvm.toolchain(
    name = "llvm_toolchain_mold",
    exec_arch = "x86_64",
    exec_os = "linux",
    linker = {"linux-x86_64": "mold"},
    llvm_version = "19.1.7",
)
use_repo(llvm, "llvm_toolchain_mold")
