# Copyright 2018 The Bazel Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_tools//tools/build_defs/repo:utils.bzl", "read_netrc", "use_netrc")
load("@helly25_bzl//bzl/versions:versions.bzl", "versions")
load(
    "@llvm_distributions_data//:data.bzl",
    "LLVM_DISTRIBUTIONS",
    "LLVM_DISTRIBUTIONS_BASE_URL",
)
load(
    "//toolchain/internal:common.bzl",
    "attr_dict",
    "exec_os_arch_dict_value",
    "host_info",
)

# The merged distribution table is built at module-load time by the
# `llvm_distributions` module extension (see
# `//toolchain/extensions:distributions.bzl`), which reads every JSONC file
# under `//toolchain/distributions/` and writes a generated `data.bzl`. Source
# files in that directory:
#   - pre_github.jsonc    - pre-GitHub releases (6.x-9.x) hosted on
#                           releases.llvm.org. Hand-maintained, frozen. This
#                           file is also the source of the per-version
#                           base_url overrides.
#   - github_legacy.jsonc - GitHub releases with the pre-19.x irregular naming
#                           (10.x-18.x). Hand-maintained, frozen.
#   - github.jsonc        - GitHub releases with the current consistent naming
#                           (19.x+). Regenerated by
#                           `utils/update_distributions.sh`.
#   - extra.jsonc         - empty by default; downstream slot for additional
#                           bundled distributions (private mirrors, internal
#                           builds, etc.).
_llvm_distributions = LLVM_DISTRIBUTIONS

# Per-version base URL override map. Lookups in `_distribution_urls` fall back
# to `_llvm_distributions_base_url_default` when a version is absent. Unlike
# the user-facing llvm_mirror attribute, these URL prefixes are not appended
# with "/" because the pre-GitHub `releases.llvm.org` URLs use a per-version
# path.
_llvm_distributions_base_url_default = "https://github.com/llvm/llvm-project/releases/download/llvmorg-"
_llvm_distributions_base_url = LLVM_DISTRIBUTIONS_BASE_URL

def _parse_version(v):
    return tuple([int(s) for s in v.split(".")])

def _version_string(version):
    return ".".join([str(v) for v in version])

def _distribution_basename(distribution):
    return distribution.split("?", 1)[0].split("#", 1)[0].split("/")[-1].split("\\")[-1].replace("%2B", "+")

def _distribution_version_string(distribution):
    # We assume here that the `distribution` contains a basename of the forms:
    # - `LLVM-<version>-...`, or
    # - `clang+llvm-<version>-...`.
    return _distribution_basename(distribution).split("-", 2)[1]

def _distribution_version(distribution):
    # Return the version string of a distribution.
    return _parse_version(_distribution_version_string(distribution))

def _get_auth(ctx, urls):
    """
    Given the list of URLs obtain the correct auth dict.

    Based on:
    https://github.com/bazelbuild/bazel/blob/793964e8e4268629d82fabbd08bf1a7718afa301/tools/build_defs/repo/http.bzl#L42
    """
    netrcpath = None
    if ctx.attr.netrc:
        netrcpath = ctx.attr.netrc
    elif not ctx.os.name.startswith("windows"):
        if "HOME" in ctx.os.environ:
            netrcpath = "%s/.netrc" % (ctx.os.environ["HOME"])
    elif "USERPROFILE" in ctx.os.environ:
        netrcpath = "%s/.netrc" % (ctx.os.environ["USERPROFILE"])

    if netrcpath and ctx.path(netrcpath).exists:
        netrc = read_netrc(ctx, netrcpath)
        return use_netrc(netrc, urls, ctx.attr.auth_patterns)

    return {}

def _strip_prefix(*, basename, strip_suffix = ""):
    for suffix in [".exe", ".tar.gz", ".tar.xz", ".tar.zst"]:
        if basename.endswith(suffix):
            return basename.removesuffix(suffix).rstrip(strip_suffix)
    fail("Unknown URL file extension {url}", url = basename)

def _full_url(url):
    if url.startswith("/"):
        return "file://" + url
    return url

def _normalize_and_check_sha256(sha256):
    if sha256:
        sha256 = sha256.removeprefix("sha256:")
        if len(sha256) != 64:
            return None, "Attribute sha256 needs exactly 64 hex characters."
    return sha256, None

def download_llvm(rctx):
    """Download the LLVM distribution for the given context."""
    urls = []
    sha256 = None
    strip_prefix = None
    key = None
    update_sha256 = False
    if rctx.attr.urls:
        urls, sha256, strip_prefix, key = _urls(rctx)
        if not sha256:
            update_sha256 = True
    if not urls:
        urls, sha256, strip_prefix = _distribution_urls(rctx)

        # The bundled distribution table provides its own sha256, so there
        # is nothing to record back into the rule's attrs. Leaving
        # update_sha256 set here would make `download_llvm` write
        # `rctx.attr.sha256[""]` post-extract and put `llvm_repo_impl` on
        # the `repo_metadata(attrs_for_reproducibility=...)` branch, which
        # `--repo_contents_cache` does not symlink-share across output
        # bases.
        update_sha256 = False

    sha256, shaerr = _normalize_and_check_sha256(sha256)
    if shaerr:
        fail("ERROR: " + shaerr)

    res = rctx.download_and_extract(
        [_full_url(url) for url in urls],
        sha256 = sha256,
        stripPrefix = strip_prefix,
        auth = _get_auth(rctx, urls),
    )

    if rctx.attr.libclang_rt:
        clang_versions = rctx.path("lib/clang").readdir()
        for libclang_rt, lib_name in rctx.attr.libclang_rt.items():
            libclang_rt_content = rctx.read(libclang_rt)
            for clang_version in clang_versions:
                lib_path = clang_version.get_child("lib", lib_name)
                rctx.file(lib_path, libclang_rt_content, legacy_utf8 = False)

    updated_attrs = attr_dict(rctx.attr)
    if update_sha256:
        updated_attrs["sha256"].update([(key, res.sha256)])
    return updated_attrs

def _key_attrs(rctx):
    key, urls = exec_os_arch_dict_value(rctx, "urls", debug = False)
    sha256 = rctx.attr.sha256.get(key, default = "")
    strip_prefix = rctx.attr.strip_prefix.get(key, default = "")
    return urls, sha256, strip_prefix, key

def _urls(rctx):
    urls, sha256, strip_prefix, key = _key_attrs(rctx)
    if not urls:
        print("LLVM archive URLs missing and no default fallback provided; will try 'distribution' attribute")  # buildifier: disable=print
    return urls, sha256, strip_prefix, key

def _get_llvm_version(rctx):
    if rctx.attr.llvm_version:
        return rctx.attr.llvm_version
    if not rctx.attr.llvm_versions:
        fail("Neither 'llvm_version' nor 'llvm_versions' given.")
    (_, llvm_version) = exec_os_arch_dict_value(rctx, "llvm_versions")
    if not llvm_version:
        info = host_info(rctx)
        fail(
            "LLVM version string missing for ({os}/{dist_name}/{dist_verison}, {arch})",
            os = info.os,
            dist_name = info.dist.name,
            dist_version = info.dist.version,
            arch = info.arch,
        )
    return llvm_version

def _get_all_llvm_distributions(*, llvm_distributions, extra_llvm_distributions, parsed_llvm_version):
    distributions = {}
    for dist, sha256 in llvm_distributions.items() + (extra_llvm_distributions.items() if extra_llvm_distributions else []):
        basename = _distribution_basename(dist)
        version = _distribution_version(basename)
        if parsed_llvm_version and parsed_llvm_version != version:
            continue
        distributions[basename] = struct(
            distribution = basename,
            sha256 = sha256,
            version = version,
        )
    return distributions

_UBUNTU_NAMES = [
    "arch",
    "chainguard",
    "linuxmint",
    "manjaro",
    "nixos",
    "pop",
    "ubuntu",
    "wolfi",
]

_UBUNTU_VERSIONS = [
    "linux-ubuntu-20.04",
    "linux-ubuntu-18.04",
    "linux-ubuntu-18.04.6",
    "linux-ubuntu-18.04.5",
    "linux-ubuntu-16.04",
    "linux-gnu-ubuntu-22.04",
    "linux-gnu-ubuntu-20.10",
    "linux-gnu-ubuntu-20.04",
    "linux-gnu-ubuntu-18.04",
    "linux-gnu-ubuntu-16.04",
    "linux-gnu-ubuntu-14.04",
    "linux-ubuntu-",  # Version prefix to catch other versions.
    "linux-gnu-ubuntu-",  # Version prefix to catch other versions.
    "linux-gnu",
    "unknown-linux-gnu",
    "unknown-linux-gnu-rhel86",
]

def _is_linux_dist(dist):
    # Note: Both Ibm-AIX and Solaris have compatibility functionality that may
    # make them accept linux code. For Solaris that stopped in newer versions.
    # For Ibm-AIX that seems uncommon, so we ask to manually specify instead of
    # manual identifying.
    if "ibm-aix" in dist.name:
        return False
    if "solaris" in dist.name:
        return False
    return True

def _dist_to_os_names(dist, default_os_names = []):
    if not _is_linux_dist(dist):
        return [dist.name]
    if dist.name in ["amzn", "suse"]:
        # For "amzn" based on the ID_LIKE field, sles seems like the closest
        # available distro for which LLVM releases are widely available.
        return [
            # The order is important here as we want to find the best match
            # without implmenting complex version comparisons.
            "linux-sles" + dist.version,
            "linux-sles12.4",
            "linux-sles12.3",
            "linux-sles12.2",
            "linux-sles11.3",
            "linux-sles",
            # The below rhel/ubuntu selection implements backwards compatibility
            # with the old predictions. However suse is not close to either. So
            # We are not using `_UBUNTU_VERSIONS` here.
            "unknown-linux-gnu-rhel86",
            "linux-gnu-ubuntu-24.04",
            "linux-gnu-ubuntu-22.04",
            "linux-gnu-ubuntu-20.04",
            "linux-gnu-ubuntu-18.04",
            "linux-gnu-ubuntu-16.04",
            "linux-gnu-ubuntu-",
        ]
    if dist.name == "centos":
        return [
            "linux-gnu",
            "unknown-linux-gnu",
            # The below ubuntu selection implements backwards compatibility
            # with the old predictions. However suse is not close to either. So
            # We are not using `_UBUNTU_VERSIONS` here.
            "linux-gnu-ubuntu-22.04",
            "linux-gnu-ubuntu-20.04",
            "linux-gnu-ubuntu-18.04",
            "linux-gnu-ubuntu-16.04",
        ]
    if dist.name == "fedora":
        return [
            "linux-gnu-Fedora27",
            "unknown-linux-gnu-rhel86",
            "linux-gnu",
            "unknown-linux-gnu",
        ] + _UBUNTU_VERSIONS
    if dist.name == "freebsd":
        return ["unknown-freebsd", "unknown-freebsd-"]
    if dist.name == "raspbian":
        return ["linux-gnueabihf", "linux-gnu"]
    if dist.name in ["rhel", "ol", "almalinux"]:
        return [
            "linux-rhel-",
            "linux-gnu-rhel-",
        ] + _UBUNTU_VERSIONS
    if dist.name == "debian":
        return [
            "linux-gnu-debian8",
        ] + _UBUNTU_VERSIONS
    if dist.name in _UBUNTU_NAMES:
        return [
            "linux-gnu-ubuntu-" + dist.version,
            "linux-ubuntu-" + dist.version,
        ] + _UBUNTU_VERSIONS
    return default_os_names

def _find_llvm_basenames_by_stem(*, prefixes, all_llvm_distributions, is_prefix = False, return_first_match = False):
    basenames = []
    for prefix in prefixes:
        for suffix in [".tar.gz", ".tar.xz"]:
            basename = prefix + suffix
            if basename in all_llvm_distributions:
                return [basename]
        if not is_prefix:
            continue
        for basename in all_llvm_distributions.keys():
            if not basename.startswith(prefix):
                continue
            for suffix in [".tar.gz", ".tar.xz"]:
                if basename.endswith(suffix) and basename not in basenames:
                    basenames.append(basename)
                    if return_first_match:
                        return basenames
    return basenames

def _find_llvm_basename_list(llvm_version, all_llvm_distributions, host_info):
    """Lookup (llvm_version, host_info) in `all_llvm_distributions.`"""
    arch = host_info.arch
    os = host_info.os
    dist = host_info.dist

    # Prefer new LLVM distributions if available
    if os != "linux" or _is_linux_dist(dist):
        basenames = _find_llvm_basenames_by_stem(
            prefixes = [
                "LLVM-{llvm_version}-{os}-{arch}".format(
                    llvm_version = llvm_version,
                    arch = {
                        "aarch64": "ARM64",
                        "x86_64": "X64",
                    }.get(arch, arch),
                    os = {
                        "darwin": "macOS",
                        "linux": "Linux",
                        "windows": "Windows",
                    }.get(os, os),
                ),
            ],
            all_llvm_distributions = all_llvm_distributions,
        )
        if basenames:
            return basenames

    # First by 'os'', then by 'dist', then the remaining Linux variants'...
    if os == "darwin":
        return _find_llvm_basenames_by_stem(
            prefixes = [
                "clang+llvm-{llvm_version}-{arch}-{os}".format(
                    llvm_version = llvm_version,
                    arch = {
                        "aarch64": "arm64",
                    }.get(arch, arch),
                    os = select_os,
                )
                for select_os in ["apple-darwin", "apple-macos", "darwin-apple"]
            ],
            all_llvm_distributions = all_llvm_distributions,
            is_prefix = True,
        )
    elif os == "windows":
        return _find_llvm_basenames_by_stem(
            prefixes = [
                "clang+llvm-{llvm_version}-{arch}-{os}".format(
                    llvm_version = llvm_version,
                    arch = arch,
                    os = "pc-windows-msvc",
                ),
            ],
            all_llvm_distributions = all_llvm_distributions,
        )
    elif dist.name == "raspbian":
        return _find_llvm_basenames_by_stem(
            prefixes = [
                "clang+llvm-{llvm_version}-{arch}-{os}".format(
                    llvm_version = llvm_version,
                    arch = arch,
                    os = select_os,
                )
                for select_os in _dist_to_os_names(dist)
            ],
            all_llvm_distributions = all_llvm_distributions,
        )
    elif os == "linux":
        if arch in ["aarch64", "armv7a", "mips", "mipsel", "sparc64", "sparcv9"]:
            arch_alias_list = {
                "sparc64": ["sparc64", "sparcv9"],
                "sparcv9": ["sparcv9", "sparc64"],
            }.get(arch, [arch])
            os_name_list = _dist_to_os_names(dist, ["linux-gnu", "unknown-linux-gnu"])
            os_name_extra_list = []
            if _is_linux_dist(dist) and [os for os in os_name_list if "linux" in os]:
                os_name_extra_list = ["linux-gnu", "unknown-linux-gnu"]
            basenames = _find_llvm_basenames_by_stem(
                prefixes = [
                    "clang+llvm-{llvm_version}-{arch}-{os}".format(
                        llvm_version = llvm_version,
                        arch = arch_alias,
                        os = os_name,
                    )
                    for arch_alias in arch_alias_list
                    for os_name in os_name_list + os_name_extra_list
                ],
                all_llvm_distributions = all_llvm_distributions,
            )
            if basenames or not os_name_list:
                return basenames
            return _find_llvm_basenames_by_stem(
                prefixes = [
                    "clang+llvm-{llvm_version}-{arch}-{os}".format(
                        llvm_version = llvm_version,
                        arch = arch_alias,
                        os = os_name,
                    )
                    for arch_alias in arch_alias_list
                    for os_name in os_name_list
                ],
                all_llvm_distributions = all_llvm_distributions,
                is_prefix = True,
            )

        arch_alias_list = {
            "x86_32": ["x86_32", "i386", "i686"],
            "x86_64": ["x86_64", "amd64"],
            "powerpc64": ["powerpc64", "final_powerpc64"],
        }.get(arch, [arch])

        prefixes = []
        for dist_name in _dist_to_os_names(dist, ["linux-gnu", "unknown-linux-gnu"]):
            for arch_alias in arch_alias_list:
                basenames = _find_llvm_basenames_by_stem(
                    prefixes = [
                        "clang+llvm-{llvm_version}-{arch}-{dist_name}{dist_version}".format(
                            llvm_version = llvm_version,
                            arch = arch_alias,
                            dist_name = dist_name,
                            dist_version = dist.version,
                        ),
                    ],
                    all_llvm_distributions = all_llvm_distributions,
                )
                if basenames:
                    return basenames
                if dist.name not in ["freebsd"]:
                    prefixes.append("clang+llvm-{llvm_version}-{arch}-{dist_name}".format(
                        llvm_version = llvm_version,
                        arch = arch_alias,
                        dist_name = dist_name,
                    ))
        return _find_llvm_basenames_by_stem(prefixes = prefixes, all_llvm_distributions = all_llvm_distributions, is_prefix = True, return_first_match = True)
    return []

def _find_llvm_basename_or_error(llvm_version, all_llvm_distributions, host_info):
    all_llvm_distributions = _filter_llvm_distributions(
        llvm_version = llvm_version,
        all_llvm_distributions = all_llvm_distributions,
    )
    basenames = _find_llvm_basename_list(llvm_version, all_llvm_distributions, host_info)
    if len(basenames) > 1:
        return None, "ERROR: Multiple configurations found for version {llvm_version} on {os}/{dist_name}/{dist_version} with arch {arch}: [{basenames}].".format(
            llvm_version = llvm_version,
            os = host_info.os,
            dist_name = host_info.dist.name,
            dist_version = host_info.dist.version,
            arch = host_info.arch,
            basenames = ", ".join(basenames),
        )
    if not basenames:
        return None, "ERROR: No matching config could be found for version {llvm_version} on {os}/{dist_name}/{dist_version} with arch {arch}.".format(
            llvm_version = llvm_version,
            os = host_info.os,
            dist_name = host_info.dist.name,
            dist_version = host_info.dist.version,
            arch = host_info.arch,
        )

    # Use the following for debugging:
    # print("Found LLVM: " + basenames[0])  # buildifier: disable=print
    if basenames[0] not in all_llvm_distributions:
        return None, "ERROR: Unknown LLVM release: %s\nPlease ensure file name is correct." % basenames[0]

    return basenames[0], None

def _is_requirement(version_or_requirements):
    """Return whether `version_or_requirements` is likely a requirement (True) or should be a version."""
    if not version_or_requirements:
        return False
    if version_or_requirements.startswith("getenv("):
        return True
    for prefix in ["first:", "latest:"]:
        if version_or_requirements.startswith(prefix) or version_or_requirements == prefix[:-1]:
            return True
    return False

def _parse_version_or_requirements(version_or_requirements):
    for prefix in ["latest:", "first:"]:
        if version_or_requirements.startswith(prefix):
            return versions.parse_requirements(version_or_requirements.removeprefix(prefix))
    if version_or_requirements in ["latest", "first"]:
        return None
    if not _is_requirement(version_or_requirements):
        return None
    fail("ERROR: Invalid version requirements: '{version_or_requirements}'.".format(
        version_or_requirements = version_or_requirements,
    ))

def _get_version_from_distribution(distribution):
    # We assume here that the `distribution` is a basename of the form `LLVM-<version>-...` or
    # `clang+llvm-<version>-...`.
    return distribution.split("-")[1]

def _get_llvm_versions(*, version_or_requirements, all_llvm_distributions):
    llvm_version_dict = {}
    for distribution in all_llvm_distributions.keys():
        version = _get_version_from_distribution(distribution)
        llvm_version_dict[_parse_version(version)] = version

    return [v for k, v in sorted(llvm_version_dict.items(), reverse = version_or_requirements.startswith("latest"))]

def _required_llvm_release_name(*, version_or_requirements, all_llvm_distributions, host_info):
    llvm_versions = _get_llvm_versions(version_or_requirements = version_or_requirements, all_llvm_distributions = all_llvm_distributions)
    requirements = _parse_version_or_requirements(version_or_requirements)
    for llvm_version in llvm_versions:
        if requirements and not versions.check_all_requirements(llvm_version, requirements):
            continue
        basenames = _find_llvm_basename_list(llvm_version, all_llvm_distributions, host_info)
        if len(basenames) == 1:
            return llvm_version, basenames[0], None
    return None, None, "ERROR: No matching distribution found."

def _resolve_llvm_version_rctx_env(rctx, llvm_version):
    if llvm_version.startswith("getenv(") and llvm_version.endswith(")"):
        env_var = llvm_version[len("getenv("):-1]
        if env_var.find(",") >= 0:
            env_name, env_default = env_var.split(",", 1)
        else:
            env_name = env_var
            env_default = None

        env_name = env_name.strip(" ")
        if not env_var:
            fail("ERROR: Bad getenv parameter '{env_var}'.".format(
                env_var = env_var,
            ))

        # We prefer 'repository_ctx.getenv' if it is available (~7.1+) and default
        # to accessing the environment directly. The latter breaks "hermeticity".
        if hasattr(rctx, "getenv"):
            llvm_version = rctx.getenv(env_name, env_default)
        elif env_name in rctx.os.environ:
            llvm_version = rctx.os.environ[env_name]
        else:
            llvm_version = env_default

        if not llvm_version:
            fail("ERROR: Empty getenv lookup for '{env_var}'.".format(
                env_var = env_var,
            ))

    return llvm_version

def _required_llvm_release_name_rctx(rctx, llvm_version):
    llvm_version = _resolve_llvm_version_rctx_env(rctx, llvm_version)
    all_llvm_distributions = _get_all_llvm_distributions(
        llvm_distributions = _llvm_distributions,
        extra_llvm_distributions = rctx.attr.extra_llvm_distributions,
        parsed_llvm_version = _parse_version(llvm_version) if not _is_requirement(llvm_version) else None,
    )
    return _required_llvm_release_name(
        version_or_requirements = llvm_version,
        all_llvm_distributions = all_llvm_distributions,
        host_info = host_info(rctx),
    )

def required_llvm_version_rctx(rctx):
    _, llvm_version = exec_os_arch_dict_value(rctx, "llvm_versions")
    if _is_requirement(llvm_version):
        llvm_version, distribution, error = _required_llvm_release_name_rctx(rctx, llvm_version)
        if error:
            fail(error)
        if llvm_version:
            print("\nINFO: Resolved latest LLVM version for {name} to {llvm_version}: {distribution}".format(
                name = rctx.attr.name,
                distribution = distribution,
                llvm_version = llvm_version,
            ))  # buildifier: disable=print
    return llvm_version

def _filter_llvm_distributions(*, llvm_version, all_llvm_distributions):
    """Return (distribution: sha) entries from `all_llvm_distributions` that match `llvm_version`."""
    result = {}
    for k, v in all_llvm_distributions.items():
        if _get_version_from_distribution(k) == llvm_version:
            result[k] = v
    return result

def _distribution_urls(rctx):
    """Return LLVM `urls`, `sha256` and `strip_prefix` for the given context."""
    llvm_version = _get_llvm_version(rctx)
    all_llvm_distributions = _get_all_llvm_distributions(
        llvm_distributions = _llvm_distributions,
        extra_llvm_distributions = rctx.attr.extra_llvm_distributions,
        parsed_llvm_version = _parse_version(llvm_version) if not _is_requirement(llvm_version) else None,
    )
    _, sha256, strip_prefix, _ = _key_attrs(rctx)

    if rctx.attr.distribution == "auto":
        rctx_host_info = host_info(rctx)
        llvm_version = _resolve_llvm_version_rctx_env(rctx, llvm_version)
        if _is_requirement(llvm_version):
            llvm_version, basename, error = _required_llvm_release_name(
                version_or_requirements = llvm_version,
                all_llvm_distributions = all_llvm_distributions,
                host_info = rctx_host_info,
            )
        else:
            basename, error = _find_llvm_basename_or_error(llvm_version, all_llvm_distributions, rctx_host_info)
        if error:
            fail(error)
        dist_info = all_llvm_distributions[basename]
        if sha256 and sha256 != dist_info.sha256:
            fail("ERROR: Attribute sha256 provided a different SHA256 than the stored one.")
        sha256 = dist_info.sha256
        distribution = dist_info.distribution
    else:
        distribution = rctx.attr.distribution
        basename = _distribution_basename(distribution)
        dist_info = all_llvm_distributions.get(basename, None)
        if sha256:
            if dist_info and sha256 != dist_info.sha256:
                fail("ERROR: Attribute sha256 provided a different SHA than the stored one.")
        elif dist_info:
            sha256 = dist_info.sha256
        else:
            fail("ERROR: Unknown LLVM release: %s\nPlease ensure file name is correct." % distribution)

    if not strip_prefix:
        strip_prefix = _strip_prefix(basename = basename, strip_suffix = "-rhel86")
    if basename != distribution:
        return [distribution], sha256, strip_prefix

    urls = []
    url_suffix = "{0}/{1}".format(llvm_version, basename).replace("+", "%2B")
    if rctx.attr.llvm_mirror:
        urls.append("{0}/{1}".format(rctx.attr.llvm_mirror, url_suffix))
    if rctx.attr.alternative_llvm_sources:
        for pattern in rctx.attr.alternative_llvm_sources:
            urls.append(pattern.format(llvm_version = llvm_version, basename = basename))
    url_base = _llvm_distributions_base_url.get(llvm_version, _llvm_distributions_base_url_default)
    urls.append(url_base + url_suffix)

    return urls, sha256, strip_prefix

def _distributions_test_writer_impl(ctx):
    """Analyze the configured versions and write to a file for test consumption.

    The test generated file '<rule_name>.out' contains the following lines:
    - a 'del:' line denotes a llvm distribution basename that was not found.
    - a 'add:' line denotes a version that was predicted but does not exist.

    Lines of type `add:` should never occur as the algorithm is supposed to
    verify that predicted distributions have been configured. Otherwise the
    algorithm could not know the hash value.
    """
    use_llvm_distributions = _llvm_distributions

    # Inject version '0.0.0' that verifies additional behavior using `extra_llvm_distributions`.
    extra_llvm_distributions = {
        "LLVM-0.0.0-Linux-ARM64.tar.xz": "a6b8679be46bdaa383e0c7f13a473ca8f7a4f87233f2cc0e0a7ab19e1b6265e7",
        "/foo/bar/LLVM-0.0.0-Linux-X64.tar.xz?xyz": "0a764a8ca521606532ca9ec4e5745c933b16b7d30f4701a47ee851d448fcdb74",
        "http://server/foo/bar/LLVM-0.0.0-macOS-ARM64.tar.xz#xyz": "9da86f64a99f5ce9b679caf54e938736ca269c5e069d0c94ad08b995c5f25c16",
        "http://server/foo/bar/LLVM-0.0.0-macOS-X64.tar.xz": "264f2f1e8b67f066749349ae8b4943d346cd44e099464164ef21b42a57663540",
        "http://server/clang%2Bllvm-0.0.0-aarch64-pc-windows-msvc.tar.xz": "5916d93bf80e3ae504022cdd8cb8887be001f9b68a7a08bd268727e8d858afa4",
        "http://server/path-to-file/clang%2Bllvm-0.0.0-x86_64-pc-windows-msvc.tar.xz#bla": "5916d93bf80e3ae504022cdd8cb8887be001f9b68a7a08bd268727e8d858afa4",
    }

    arch_list = [
        "aarch64",
        "armv7a",
        "mips",
        "mipsel",
        "powerpc64",
        "powerpc64le",
        "sparc64",
        "sparcv9",
        "x86_32",
        "x86_64",
    ]
    arch_alias_dict = {
        "sparc64": ["sparc64", "sparcv9"],
        "sparcv9": ["sparcv9", "sparc64"],
    }
    os_list = [
        "darwin",
        "linux",
        "windows",
    ]
    ANY_VERSION = "0"  # Version does not matter, but must be a valid integer
    dist_dict_list = {
        "linux": [
            # keep sorted
            struct(name = "amzn", version = ANY_VERSION),
            struct(name = "arch", version = ANY_VERSION),
            struct(name = "centos", version = "6"),
            struct(name = "centos", version = "7"),
            struct(name = "chainguard", version = ANY_VERSION),
            struct(name = "debian", version = "0"),
            struct(name = "debian", version = "8"),
            struct(name = "debian", version = "9"),
            struct(name = "fedora", version = "26"),
            struct(name = "fedora", version = "27"),
            struct(name = "fedora", version = "42"),
            struct(name = "freebsd", version = "10"),
            struct(name = "freebsd", version = "11"),
            struct(name = "freebsd", version = "12"),
            struct(name = "freebsd", version = "13"),
            struct(name = "ibm-aix", version = "7.2"),
            struct(name = "linuxmint", version = "18"),
            struct(name = "linuxmint", version = "19"),
            struct(name = "pc-solaris", version = "2.11"),
            struct(name = "raspbian", version = ANY_VERSION),
            struct(name = "rhel", version = ANY_VERSION),
            struct(name = "sun-solaris", version = "2.11"),
            struct(name = "suse", version = "11.3"),
            struct(name = "suse", version = "12.2"),
            struct(name = "suse", version = "12.3"),
            struct(name = "suse", version = "12.4"),
            struct(name = "suse", version = "15.5"),
            struct(name = "suse", version = "16.0"),
            struct(name = "suse", version = "17.0"),
            struct(name = "ubuntu", version = "14.04"),
            struct(name = "ubuntu", version = "16.04"),
            struct(name = "ubuntu", version = "18.04.5"),
            struct(name = "ubuntu", version = "18.04.6"),
            struct(name = "ubuntu", version = "18.04"),
            struct(name = "ubuntu", version = "20.04"),
            struct(name = "ubuntu", version = "20.10"),
            struct(name = "ubuntu", version = "22.04"),
            struct(name = "ubuntu", version = "24.04"),
            struct(name = "void", version = ANY_VERSION),
            struct(name = "wolfi", version = ANY_VERSION),
        ],
    }

    # Define the min real version. For earlier injected versions we do no perform dist testing.
    MIN_VERSION = _parse_version("6.0.0")

    # Additional output will be generated for versions up to and including `MAX_VERSION`
    MAX_VERSION = _parse_version("20.1.3")
    version_dict = {
        _distribution_version(basename): None
        for basename in use_llvm_distributions.keys() + extra_llvm_distributions.keys()
    } | {
        _parse_version(v): None
        for v in _llvm_distributions_base_url.keys()
    }
    versions = sorted(version_dict.keys())

    # Write versions to output to check which versions we take into account.
    output = []
    select = []
    for version in versions:
        output.append("version: " + _version_string(version))

    # We keep track of versions in `not_found` and remove the ones we found.
    # So at the end all version that were not found remain, hence the name.
    not_found = {
        _distribution_basename(distribution): None
        for distribution in use_llvm_distributions.keys() + extra_llvm_distributions.keys()
    }

    # While computing we add predicted versions that are not configured as True.
    # At the end we add the not-found versions as False.
    result = {}

    # Collect cases that produce duplicates (or multiple) basenames.
    dupes = []

    # For all versions X arch X os check if we can compute the distribution.
    for version in versions:
        all_llvm_distributions = _get_all_llvm_distributions(
            llvm_distributions = use_llvm_distributions,
            extra_llvm_distributions = extra_llvm_distributions,
            parsed_llvm_version = version,
        )
        for basename, distribution in all_llvm_distributions.items():
            _, shaerr = _normalize_and_check_sha256(distribution.sha256)
            if shaerr:
                output.append("err: {basename}: bad sha256: {shaerr}".format(
                    basename = basename,
                    shaerr = shaerr,
                ))
        for arch in arch_list:
            for os in os_list:
                if version < MIN_VERSION:
                    # Limit the injected version checks
                    if arch not in ["aarch64", "x86_64"]:
                        break
                    dist_list = [struct(name = os, version = "")]
                else:
                    dist_list = dist_dict_list.get(os, [struct(name = os, version = "")])
                for dist in dist_list:
                    if arch == "sparc64" and dist.name != "sun-solaris":
                        # Sparc64 and SparcV9 are handled in the same way, just different precedence.
                        # One is the architecture th other the ISA. Restrict to one to limit output.
                        continue
                    host_info = struct(
                        arch = arch,
                        os = os,
                        dist = dist,
                    )
                    basenames = _find_llvm_basename_list(_version_string(version), all_llvm_distributions, host_info)
                    if version <= MAX_VERSION:
                        predicted, error = _find_llvm_basename_or_error(
                            _version_string(version),
                            all_llvm_distributions,
                            host_info,
                        )
                        skip_output = False
                        if error:
                            if error.startswith("ERROR: No matching config could be found for version"):
                                skip_output = True
                        else:
                            if predicted.endswith(".exe"):
                                error = "ERROR: Windows .exe is not supported: " + predicted
                            elif predicted not in all_llvm_distributions:
                                error = "ERROR: Unavailable prediction: " + predicted
                            elif len(basenames) == 0:
                                skip_output = True
                            elif len(basenames) == 1:
                                predicted = basenames[0]
                            else:
                                error = "ERROR: Multiple selections"
                            if not error:
                                arch_found = [arch for arch in arch_list if arch in predicted]
                                if len(arch_found) == 1 and arch_found[0] not in arch_alias_dict.get(arch, [arch]):
                                    error = "ERROR: Bad arch selection: " + predicted
                        if not skip_output:
                            select.append("{version}-{arch}-{os}/{dist_name}/{dist_version} -> {basename}".format(
                                version = _version_string(version),
                                arch = arch,
                                os = os,
                                dist_name = dist.name,
                                dist_version = dist.version,
                                basename = error or predicted,
                            ))
                    if len(basenames) != 1:
                        if basenames:
                            dupes.append("dup: {version}-{arch}-{os}-{dist_name}-{dist_version} -> {count}".format(
                                version = _version_string(version),
                                arch = arch,
                                os = os,
                                dist_name = dist.name,
                                dist_version = dist.version,
                                count = len(basenames),
                            ))
                            dupes.extend(["   : " + basename for basename in basenames])
                        continue
                    basename = basenames[0]
                    if basename in all_llvm_distributions:
                        if basename in not_found:
                            not_found.pop(basename)
                    else:
                        result[basename] = True

    # Build result
    for dist in not_found:
        result[dist] = False
    output += [("add: " if found else "del: ") + dist for dist, found in result.items()]
    output += dupes
    ctx.actions.write(ctx.outputs.output, "\n".join(output) + "\n")
    ctx.actions.write(ctx.outputs.select, "\n".join(select) + "\n")

distributions_test_writer = rule(
    implementation = _distributions_test_writer_impl,
    attrs = {
        "output": attr.output(mandatory = True),
        "select": attr.output(mandatory = True),
    },
)

def _requirements_test_writer_impl(ctx):
    """Analyze the configured versions and write to a file for test consumption.
    The test generated file '<rule_name>.out' contains the following lines:
    [<arch>,<os>,<requirement>]: <llvm_distribution_basename>
    """
    all_llvm_distributions = {
        # In order to prevent new distributions to interfere we cut at 20.1.3.
        k: v
        for k, v in _llvm_distributions.items()
        if _parse_version(_get_version_from_distribution(k)) <= (20, 1, 3)
    }
    requirement_list = [
        "latest:<=20.1.0",
        "latest:<=20.1.0,>17.0.4,!=19.1.7",
        "latest:<20.1.0,>17.0.4,!=19.1.7",
        "latest:<20.1.0,>17.0.4",
        "latest:>=15.0.6,<16",
        "first:>=15.0.6,<16",
        "latest",
        "first",
    ]
    arch_list = [
        "aarch64",
        "armv7a",
        "x86_64",
    ]
    os_list = [
        "darwin",
        "linux",
        "windows",
    ]
    ANY_VERSION = "0"  # Version does not matter, but must be a valid integer
    dist_dict_list = {
        "linux": [
            # keep sorted
            struct(name = "ubuntu", version = ANY_VERSION),
            struct(name = "raspbian", version = ANY_VERSION),
            struct(name = "rhel", version = ANY_VERSION),
        ],
    }
    result = []
    for arch in arch_list:
        for os in os_list:
            dist_list = dist_dict_list.get(os, [struct(name = os, version = "")])
            for dist in dist_list:
                for requirement in requirement_list:
                    host_info = struct(
                        arch = arch,
                        os = os,
                        dist = dist,
                    )
                    llvm_version, basename, error = _required_llvm_release_name(
                        version_or_requirements = requirement,
                        all_llvm_distributions = all_llvm_distributions,
                        host_info = host_info,
                    )
                    if llvm_version and basename:
                        result.append("[{arch},{os}{dist_name}{dist_version},'{requirement}']: {llvm_version} = {basename}".format(
                            arch = arch,
                            os = os,
                            dist_name = "," + dist.name if os == "linux" else "",
                            dist_version = "," + dist.version if os == "linux" else "",
                            requirement = requirement,
                            llvm_version = llvm_version,
                            basename = basename,
                        ))
                    else:
                        result.append("[{arch},{os},\"{requirement}\"]: {error}".format(
                            arch = arch,
                            os = os,
                            requirement = requirement,
                            llvm_version = llvm_version,
                            basename = basename,
                            error = error or "ERROR: N/A",
                        ))
    ctx.actions.write(ctx.outputs.result, "\n".join(result) + "\n")

requirements_test_writer = rule(
    implementation = _requirements_test_writer_impl,
    attrs = {
        "result": attr.output(mandatory = True),
    },
)
