# Copyright 2026 The Bazel Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "feature_override_tests")

local_repository(
    name = "toolchains_llvm",
    path = "../..",
)

load("@toolchains_llvm//toolchain:deps.bzl", "bazel_toolchain_dependencies")

bazel_toolchain_dependencies()

load("@bazel_features//:deps.bzl", "bazel_features_deps")

bazel_features_deps()

load("@rules_cc//cc:extensions.bzl", "compatibility_proxy_repo")

compatibility_proxy_repo()

load("@toolchains_llvm//toolchain:rules.bzl", "llvm_feature_override", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    cxx_standard = {"": "c++17"},
    extra_compile_flags = {"": ["-DBASE_TOOLCHAIN=1"]},
    feature_overrides = [
        llvm_feature_override(
            cxx_standard = {"": "c++20"},
            extra_compile_flags = {"": [
                "-DFEATURE_TOOLCHAIN=1",
                "@override_input.rsp",
            ]},
            extra_compiler_files = "//:override_input.rsp",
            features = [
                "test_override",
                "test_second",
                "-test_disable",
                "-test_distribution",
                "-thin_lto",
            ],
            targets = [
                "darwin-aarch64",
                "darwin-x86_64",
                "linux-x86_64",
            ],
        ),
        llvm_feature_override(
            features = [
                "test_distribution",
                "-test_override",
                "-thin_lto",
            ],
            llvm_version = "22.1.8",
            reset = ["extra_compile_flags"],
        ),
        llvm_feature_override(
            features = [
                "thin_lto",
                "-test_override",
                "-test_distribution",
            ],
            linker = {"linux-x86_64": ""},
        ),
    ],
    linker = {
        "darwin-aarch64": "auto",
        "darwin-x86_64": "auto",
        "linux-x86_64": "mold",
    },
    linker_version = "2.40.4",
    llvm_version = "23.1.2",
)

load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")

llvm_register_toolchains()
